// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    $("#jobs-more-link").click(function(event) {
      $("#jobs-more").slideDown();
      $("#jobs-more-link").hide();
      return event.preventDefault();
    });
    new Highcharts.Chart({
      chart: {
        renderTo: "graph",
        margin: [0, 0, 0, 0],
        plotBorderWidth: 0,
        plotShadow: false
      },
      title: {
        align: "center",
        floating: false,
        text: ""
      },
      credits: {
        enabled: false
      },
      tooltip: {
        formatter: function() {
          return "<b>" + this.series.name + "</b><br/>" + this.point.name + ": " + this.y + " %";
        }
      },
      series: [
        {
          type: "pie",
          name: "Core Expertice",
          size: "50%",
          data: [
            {
              name: "Ruby /<br/> RoR",
              y: 40
            }, {
              name: "JavaScript",
              y: 20
            }, {
              name: "Python",
              y: 10
            }, {
              name: "C",
              y: 10
            }, {
              name: "Java",
              y: 10
            }, {
              name: "Others",
              y: 10
            }
          ],
          dataLabels: {
            enabled: true
          }
        }
      ]
    });
    return $.ajax({
      url: "https://api.github.com/repos/hannu/hannu.github.com/commits",
      data: {
        per_page: 1
      },
      dataType: "jsonp",
      type: "get"
    }).success(function(response) {
      var date, e;
      if (response.data.length > 0) {
        date = new Date(response.data[0].commit.committer.date);
        e = $("<p />").html("Latest change " + date.getDate() + "." + date.getMonth() + "." + date.getFullYear() + ": " + "<a href=\"https://github.com/hannu/hannu.github.com/commit/" + response.data[0].sha + "\">" + response.data[0].commit.message + "</a>");
        return $("#git-details").append(e);
      }
    });
  });

}).call(this);
